blank_issues_enabled: false
contact_links:
  - name: New feature / UI suggestion
    url: https://github.com/damontecres/Wholphin/discussions/new?category=ideas
    about: Please request new features here
  - name: Questions
    url: https://github.com/damontecres/Wholphin/discussions/new?category=general
    about: Please ask questions here
