title: Wholphin
email: damontecres@gmail.com
description: >-
  Wholphin is an OSS Android TV client for Jellyfin
domain: damontecres.github.io
baseurl: "/Wholphin"
url: "https://damontecres.github.io"
github_username:  damontecres

# Build settings
theme: minima
plugins:
  - jekyll-feed
